### ISSUE TITLE
Adding productivity scores

### ISSUE THREAD

**Issue by saltperfect** [sayanarijit/mind#44]
Can we add productivity score in it?
Also we can add categories to task to understand which type of task is a person most likely to do?

**Comment by sayanarijit** [comment]
Hi. Thanks for the suggestion.

As for productivity score, I think the colors represent all I'd want to know about my productivity score.

Green - All well
Light Green - Procrastinating
Yellow - Procrastinating too much
Orange - Better finish it now
Red - Scrap it! Forget about the backlog and start a new life.

If by score, you meant some exact number, maybe, if you have some idea, you can suggest. But personally, I prefer colors than exact numbers.

About categories, I think we can always prepend it in the title, e.g. `CATEGORY: Some Task`. This is as simple as it can get.
To filter tasks from a category, we can use grep.

```
mind | grep 'CATEGORY:'
```

Anyway, the point is to have as little tasks in the list as possible, so, if I have too many tasks queued up that I need to categorize them, maybe it's not working me.

**Comment by sayanarijit** [comment]
@saltperfect about categories, what we can do instead is rendering emojis. For e.g. `:workout:` will display 🏋️ .

E.g.

I type

```
:workout: Register at the local gym
```

I see

🏋️ Register at the local gym

**Comment by sayanarijit** [comment]
being able use custom use a custom emoji using some config file would be even nicer.

**Comment by saltperfect** [comment]
By productivity score, I mean at the end of the day I should have details about how much time a particular task was waiting in the stack. By looking at these data at the end of day I can infer I took long time to complete a simple task.

**Comment by sayanarijit** [comment]
Ah so you meant you want to display the time taken for each completed tasks. I think that can be useful to some users.
So, how do you plan to do that? Adding end time to each task or creating a separate "history.yml" file with the timestamps?

**Comment by saltperfect** [comment]
Currently I am working on Go and go related projects and wouldn't know where to start contributing to the project. I just use the tool to track my progress.

**Comment by sayanarijit** [comment]
My bad, I wasn't clear. I was looking for feedback on how you'd like to see the time taken for each task. Don't worry, I got some idea. I'll explain it soon.

**Comment by sayanarijit** [comment]
I'm halting/closing this project as this workflow doesn't work for me anymore.

The marketing guys / media are getting really good at their game and so, I need to develop a new, super secret, anti-destraction workflow which is beyond this dimension. I won't be posting about it, and definitely won't be making a public project implementing the workflow anytime soon.

Good luck people. Thanks for using mind.
